// Next-pass probe candidates — generated by harness-evolve.ts
// Date: 2026-04-13T01:11:37.036Z
// Copy relevant entries into scripts/harness-probe-wide.ts or harness-probe-confirm.ts

// ── Candidate 1 ──
// DRILL-DOWN: confirm-w2-no-ics-baseline exceeded maxIterations (got 9, expected ≤5)
// Targets: does maxIterations hard stop work? Is ICS redirect loop involved?
{
  id: "confirm-w2-no-ics-baseline-maxiter-drill",
  strategy: "reactive",
  maxIterations: 3,
  useMaxIterationsDirect: true,  // use .withMaxIterations() not withReasoning()
  allowedTools: [],
  task: "Explain recursion in one sentence.",
  expectation: "Hard stop at maxIterations=3. Confirms kernel loop respects limit.",
}

// ── Candidate 2 ──
// DRILL-DOWN: confirm-w4-reasoning-opt-maxiter exceeded maxIterations (got 16, expected ≤3)
// Targets: does maxIterations hard stop work? Is ICS redirect loop involved?
{
  id: "confirm-w4-reasoning-opt-maxiter-maxiter-drill",
  strategy: "reactive",
  maxIterations: 3,
  useMaxIterationsDirect: true,  // use .withMaxIterations() not withReasoning()
  allowedTools: [],
  task: "Explain recursion in one sentence.",
  expectation: "Hard stop at maxIterations=3. Confirms kernel loop respects limit.",
}

// ── Candidate 3 ──
// DRILL-DOWN: termination-quality exceeded maxIterations (got 41, expected ≤14)
// Targets: does maxIterations hard stop work? Is ICS redirect loop involved?
{
  id: "termination-quality-maxiter-drill",
  strategy: "reactive",
  maxIterations: 3,
  useMaxIterationsDirect: true,  // use .withMaxIterations() not withReasoning()
  allowedTools: [],
  task: "Explain recursion in one sentence.",
  expectation: "Hard stop at maxIterations=3. Confirms kernel loop respects limit.",
}

// ── Candidate 4 ──
// DRILL-DOWN: tool-heavy had zero act phases (expected ≥1)
// Targets: is FC parsing broken (W1)? Are tools in allowedTools but not being parsed?
// Compare: native FC model (qwen3:14b) vs text-format model (cogito:8b)
{
  id: "tool-heavy-fc-drill",
  strategy: "reactive",
  maxIterations: 4,
  allowedTools: ["web-search"],
  task: 'Call web-search with query "test query". Return the raw result.',
  expectation: "actPhaseCount ≥ 1. If 0 with cogito → W1 confirmed. If 0 with qwen3 → deeper FC bug.",
}

// ── Candidate 5 ──
// DRILL-DOWN: wide-direct-answer-efficiency exceeded maxIterations (got 6, expected ≤1)
// Targets: does maxIterations hard stop work? Is ICS redirect loop involved?
{
  id: "wide-direct-answer-efficiency-maxiter-drill",
  strategy: "reactive",
  maxIterations: 1,
  useMaxIterationsDirect: true,  // use .withMaxIterations() not withReasoning()
  allowedTools: [],
  task: "Explain recursion in one sentence.",
  expectation: "Hard stop at maxIterations=1. Confirms kernel loop respects limit.",
}
