import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["esm"],
  dts: true,
  clean: true,
  splitting: false,
  sourcemap: true,
  banner: { js: "#!/usr/bin/env bun" },
  external: [
    "effect",
    "@reactive-agents/core",
    "@reactive-agents/runtime",
    "@reactive-agents/runtime-shim",
    "@reactive-agents/benchmarks",
    "@reactive-agents/eval",
    "@reactive-agents/llm-provider",
    "@reactive-agents/a2a",
    "@reactive-agents/trace",
    "@reactive-agents/tools",
    "@reactive-agents/cortex",
    "@reactive-agents/diagnose",
    "@reactive-agents/memory",
    "bun:sqlite",
    "chalk",
    "ora",
    "boxen",
  ],
});
